# Generated by Django 4.2.3 on 2024-08-08 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='travelpost',
            name='category',
            field=models.CharField(default='Travel', max_length=20),
        ),
    ]
