# Generated by Django 4.2.3 on 2023-08-02 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_tag_travelpost_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='travelpost',
            name='tags',
            field=models.ManyToManyField(blank=True, null=True, to='base.tag'),
        ),
    ]
