# Generated by Django 4.2.3 on 2024-08-08 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_comment_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='vote_post',
        ),
        migrations.AddField(
            model_name='comment',
            name='vote',
            field=models.CharField(blank=True, choices=[('up', 'Up Vote'), ('down', 'Down Vote')], max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='travelpost',
            name='vote',
            field=models.CharField(blank=True, choices=[('up', 'Up Vote'), ('down', 'Down Vote')], max_length=200, null=True),
        ),
    ]
