# Generated by Django 4.2.3 on 2024-08-08 22:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_remove_comment_vote_post_comment_vote_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-created']},
        ),
    ]
