# Generated by Django 4.2.3 on 2023-08-03 18:25

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_travelpost_votes_total_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='travelpost',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
