# Generated by Django 4.2.3 on 2023-08-03 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_alter_travelpost_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='travelpost',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
