# Generated by Django 4.2.3 on 2023-08-10 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_alter_travelpost_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='travelpost',
            name='image',
            field=models.ImageField(blank=True, default='default_post_img.jpg', null=True, upload_to=''),
        ),
    ]
