# Generated by Django 4.2.3 on 2023-08-20 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_alter_travelpost_name_alter_travelpost_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='text',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
