# Generated by Django 4.2.3 on 2023-09-23 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_travelpost_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='travelpost',
            name='tags',
            field=models.ManyToManyField(blank=True, to='base.tag'),
        ),
    ]
